# This is a basic workflow to help you get started with Actions
name: CI-Pipeline
# Controls when the workflow will run
on: push
# Allows you to run this workflow manually from the Actions tab
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '20'
            - name: install
              run: npm install
            - name: ESLint
              run: npm run lint
            - name: Prettier
              run: npx prettier --write .
